version: "3.9"

volumes:
  db-data:
    external: false
  redis-data:

services:
  mysql8_0:
    image: mysql:8.0
    volumes:
      - db-data: /var/lib/mysql
      - ./mysql:/etc/mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: "Asia/Seoul"


  redis:
    image: redis:5.0-buster
    volumes:
    - redis-data: /data
    - ./redis/data:/data
    ports:
    - "6379:6379"