spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments : false

    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/purchaselist?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwer1234